USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON FPVCATEGORY
REBUILD;
ALTER INDEX ALL ON FPVCOUNTRY
REBUILD;
ALTER INDEX ALL ON FPVITEM
REBUILD;
ALTER INDEX ALL ON FPVPERSON
REBUILD;
ALTER INDEX ALL ON FPVPERSONPSW
REBUILD;
ALTER INDEX ALL ON FPVSUBCATEGORY
REBUILD;
ALTER INDEX ALL ON FPVBRAND
REBUILD;
ALTER INDEX ALL ON FPVSTORE
REBUILD;
ALTER INDEX ALL ON FPVPHOTOALBUM
REBUILD;
ALTER INDEX ALL ON FPVINVOICE
REBUILD;
GO