
--ASYNCPROCESS | Ver.: 2501
UPDATE [ASYNCPROCESS]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [ASYNCPROCESS]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--ASYNCPROCESSARGUMENT | Ver.: 2501
UPDATE [ASYNCPROCESSARGUMENT]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--ASYNCPROCESSATTACHMENTS | Ver.: 2501
UPDATE [ASYNCPROCESSATTACHMENTS]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--USERAUTHORIZATION | Ver.: 2501
UPDATE [USERAUTHORIZATION]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--FPVPERSONPSW | Ver.: 2508
UPDATE [FPVPERSONPSW]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
UPDATE [FPVPERSONPSW]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--FPVSUBCATEGORY | Ver.: 2508
UPDATE [FPVSUBCATEGORY]
SET [CATEGORY] = NULL
where [CATEGORY] in (0);
GO
--FPVITEM | Ver.: 2514
UPDATE [FPVITEM]
SET [BRAND] = NULL
where [BRAND] in (0);
UPDATE [FPVITEM]
SET [CATEGORY] = NULL
where [CATEGORY] in (0);
UPDATE [FPVITEM]
SET [SUBCATEGORY] = NULL
where [SUBCATEGORY] in (0);
UPDATE [FPVITEM]
SET [INVOICE] = NULL
where [INVOICE] in (0);
UPDATE [FPVITEM]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
GO
--FPVPHOTOALBUM | Ver.: 2514
UPDATE [FPVPHOTOALBUM]
SET [ITEM] = NULL
where [ITEM] in (0);
UPDATE [FPVPHOTOALBUM]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
GO
--FPVINVOICE | Ver.: 2516
UPDATE [FPVINVOICE]
SET [STORE] = NULL
where [STORE] in (0);
UPDATE [FPVINVOICE]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
GO
--FPVSTORE | Ver.: 2518
UPDATE [FPVSTORE]
SET [COUNTRY] = NULL
where [COUNTRY] in (0);
UPDATE [FPVSTORE]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
GO
--FPVBRAND | Ver.: 2519
UPDATE [FPVBRAND]
SET [COUNTRY] = NULL
where [COUNTRY] in (0);
UPDATE [FPVBRAND]
SET [CODPERSON] = NULL
where [CODPERSON] in (0);
GO


